set autoread
set completeopt=menu,menuone,noselect
set cursorline
set expandtab
set foldmethod=indent
set ignorecase
set matchtime=3
set nofoldenable
set nowrap
set number
set mouse=
set numberwidth=4
set relativenumber
set scrolloff=10
set shiftround
set shiftwidth=2
set smartcase
set tabstop=2
set termguicolors
colorscheme dracula

