set autoread
set colorcolumn=80
set completeopt=menu,menuone,noselect
set cursorcolumn
set cursorline
set expandtab
set foldmethod=indent
set ignorecase
set matchtime=3
set mouse=
set nofoldenable
set nowrap
set number
set numberwidth=4
set relativenumber
set scrolloff=10
set shiftround
set shiftwidth=2
set smartcase
set tabstop=2
